<a href="https://colab.research.google.com/github/shubhamgogri/Python--DS/blob/main/Coursera/Deep%20Learning/ANN_Bank_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

###Part 1 - Data Preprocessing
Importing the dataset

In [23]:
 data = pd.read_csv("https://raw.githubusercontent.com/shubhamgogri/Python--DS/main/Coursera/Deep%20Learning/Churn_Modelling.csv")
 data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

Don't need RowNumber, CustomerId, Surname 

In [24]:
Y = data.iloc[:,-1]
X = data.iloc[:, 3:-1]

In [25]:
X.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

Splitted the independent and dependent data


Encoding categorical data -- Geographical


In [26]:
from sklearn.preprocessing import LabelEncoder

In [31]:
le = LabelEncoder()
X["Gender"] = le.fit_transform(X["Gender"])

In [32]:
X["Gender"].unique()

array([0, 1])

In [33]:
X["Gender"].head()

0    0
1    0
2    0
3    0
4    0
Name: Gender, dtype: int64

0 for Female 
1 for Male


One Hot encding for Geography

In [30]:
from sklearn.preprocessing import OneHotEncoder

o_encoder = OneHotEncoder()

In [44]:
geography = pd.get_dummies(X['Geography'], drop_first= True)
geography

Germany  Spain
0           0      0
1           0      1
2           0      0
3           0      0
4           0      1
...       ...    ...
9995        0      0
9996        0      0
9997        0      0
9998        1      0
9999        0      0

[10000 rows x 2 columns]

In [48]:
X = pd.concat([X, geography], axis = 1)

In [49]:
X.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France       0   42       2       0.00              1   
1          608     Spain       0   41       1   83807.86              1   
2          502    France       0   42       8  159660.80              3   
3          699    France       0   39       1       0.00              2   
4          850     Spain       0   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Germany  Spain  
0          1               1        101348.88        0      0  
1          0               1        112542.58        0      1  
2          1               0        113931.57        0      0  
3          0               0         93826.63        0      0  
4          1               1         79084.10        0      1

In [51]:
# drop original column...
X.drop(["Geography"], axis = 1, inplace = True)

In [52]:
X.head()

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619       0   42       2       0.00              1          1   
1          608       0   41       1   83807.86              1          0   
2          502       0   42       8  159660.80              3          1   
3          699       0   39       1       0.00              2          0   
4          850       0   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Germany  Spain  
0               1        101348.88        0      0  
1               1        112542.58        0      1  
2               0        113931.57        0      0  
3               0         93826.63        0      0  
4               1         79084.10        0      1

In [53]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   CreditScore      10000 non-null  int64  
 1   Gender           10000 non-null  int64  
 2   Age              10000 non-null  int64  
 3   Tenure           10000 non-null  int64  
 4   Balance          10000 non-null  float64
 5   NumOfProducts    10000 non-null  int64  
 6   HasCrCard        10000 non-null  int64  
 7   IsActiveMember   10000 non-null  int64  
 8   EstimatedSalary  10000 non-null  float64
 9   Germany          10000 non-null  uint8  
 10  Spain            10000 non-null  uint8  
dtypes: float64(2), int64(7), uint8(2)
memory usage: 722.8 KB


In [54]:
X['Germany'] = X['Germany'].astype(int)
X['Spain'] = X['Spain'].astype(int)

In [55]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   CreditScore      10000 non-null  int64  
 1   Gender           10000 non-null  int64  
 2   Age              10000 non-null  int64  
 3   Tenure           10000 non-null  int64  
 4   Balance          10000 non-null  float64
 5   NumOfProducts    10000 non-null  int64  
 6   HasCrCard        10000 non-null  int64  
 7   IsActiveMember   10000 non-null  int64  
 8   EstimatedSalary  10000 non-null  float64
 9   Germany          10000 non-null  int64  
 10  Spain            10000 non-null  int64  
dtypes: float64(2), int64(9)
memory usage: 859.5 KB


Now all features are in numeric format...

###Splitting the dataset into the Training set and Test set


In [57]:
from sklearn.model_selection import train_test_split

In [58]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = .2, random_state = 0)

###Feature Scaling
Must for ANN Models

In [59]:
from sklearn.preprocessing import StandardScaler

In [60]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

###Part 2 - Building the ANN
Initializing the ANN

In [61]:
import tensorflow as tf

In [70]:
tf.__version__

'2.9.2'

In [71]:
ann = tf.keras.models.Sequential()  

Adding the input layer and the first hidden layer


In [72]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

Adding the second hidden layer


In [73]:
ann.add(tf.keras.layers.Dense(units = 6 , activation = 'relu'))

Adding the output layer


In [74]:
ann.add(tf.keras.layers.Dense(units = 1 , activation = 'sigmoid'))
# binary = sigmoid
# category = softmax

###Part 3 - Training the ANN
Compiling the ANN

In [75]:
ann.compile(optimizer = 'adam', loss= 'binary_crossentropy', metrics = ['accuracy'])
# binary = binary_crossentropy
# category = category_crossentropy

In [76]:
ann.fit(X_train, y_train, batch_size= 32, epochs = 300)

Epoch 1/300
250/250 [==============================] - 2s 2ms/step - loss: 0.5989 - accuracy: 0.7426
Epoch 2/300
250/250 [==============================] - 1s 2ms/step - loss: 0.5024 - accuracy: 0.7960
Epoch 3/300
250/250 [==============================] - 0s 2ms/step - loss: 0.4720 - accuracy: 0.7960
Epoch 4/300
250/250 [==============================] - 1s 2ms/step - loss: 0.4559 - accuracy: 0.7959
Epoch 5/300
250/250 [==============================] - 1s 2ms/step - loss: 0.4400 - accuracy: 0.8002
Epoch 6/300
250/250 [==============================] - 1s 2ms/step - loss: 0.4250 - accuracy: 0.8120
Epoch 7/300
250/250 [==============================] - 0s 2ms/step - loss: 0.4160 - accuracy: 0.8221
Epoch 8/300
250/250 [==============================] - 0s 2ms/step - loss: 0.4107 - accuracy: 0.8226
Epoch 9/300
250/250 [==============================] - 0s 2ms/step - loss: 0.4071 - accuracy: 0.8232
Epoch 10/300
250/250 [==============================] - 0s 2ms/step - loss: 0.4037 - accura

Predicting for a single customer


Use our ANN model to predict if the customer with the following informations will leave the bank:

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: $ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: $ 50000

So, should we say goodbye to that customer ?

In [77]:
X.head()

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619       0   42       2       0.00              1          1   
1          608       0   41       1   83807.86              1          0   
2          502       0   42       8  159660.80              3          1   
3          699       0   39       1       0.00              2          0   
4          850       0   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Germany  Spain  
0               1        101348.88        0      0  
1               1        112542.58        0      1  
2               0        113931.57        0      0  
3               0         93826.63        0      0  
4               1         79084.10        0      1

In [82]:
test_sit = np.array([600, 1,40,3,60000, 2,1,1, 50000, 0,0])

In [88]:
pred = ann.predict(sc.transform([[600, 1,40,3,60000, 2,1,1, 50000, 0,0]]))

1/1 [==============================] - 0s 64ms/step


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


imp to scale the input for this test cause the training was done on scaled data.

In [89]:
pred

array([[0.08026956]], dtype=float32)

Hence the customer will not leave the bank 

#Predicting the Test set results


In [109]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)

63/63 [==============================] - 0s 2ms/step


Confusion Matrix to see the performace on test data

In [110]:
y_test.head()

9394    0
898     1
2398    0
5906    0
2343    0
Name: Exited, dtype: int64

In [111]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [112]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
cm

array([[1480,  115],
       [ 253,  152]])

In [113]:
accuracy_score(y_test,y_pred )

0.816

In [114]:
ann.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 6)                 72        
                                                                 
 dense_5 (Dense)             (None, 6)                 42        
                                                                 
 dense_6 (Dense)             (None, 1)                 7         
                                                                 
Total params: 121
Trainable params: 121
Non-trainable params: 0
_________________________________________________________________
