<a href="https://colab.research.google.com/github/shubhamgogri/Python--DS/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [ ]:
list = [1,4,2,5,6]
arr = np.array(list)
print(arr)

[1 4 2 5 6]


In [ ]:
type(arr)
arr

array([1, 4, 2, 5, 6])

In [ ]:
#shape
arr.shape

(5,)

In [ ]:
#two dimension array
list1 = [1,2,4,5]
list2 = [5,6,4,4]
list3 = [4,8,6,9]
list4 = [8,5 ,4,6]
arr = np.array([list1, list2,list3,list4])

In [ ]:
arr

array([[1, 2, 4, 5],
       [5, 6, 4, 4],
       [4, 8, 6, 9],
       [8, 5, 4, 6]])

In [ ]:
arr.shape

(4, 4)

In [ ]:
arr.reshape(2,2,4)
arr
# total count should be 12 i.e 3*4, 3*2*2
# 1st 2[ 2nd 2 [ [4]  ]  ]

array([[[1, 2, 4, 5],
        [5, 6, 4, 4]],

       [[4, 8, 6, 9],
        [8, 5, 4, 6]]])

In [ ]:
print("arr[0][0]")
print(arr[0][0])
print("arr[0]")
print(arr[0])
print("arr")
print(arr)

arr[0][0]
[1 2 4 5]
arr[0]
[[1 2 4 5]
 [5 6 4 4]]
arr
[[[1 2 4 5]
  [5 6 4 4]]

 [[4 8 6 9]
  [8 5 4 6]]]


Indexing


In [ ]:
arr[:,:]
# row,column
# all the elements  

array([[1, 2, 4, 5],
       [5, 6, 4, 4],
       [4, 8, 6, 9],
       [8, 5, 4, 6]])

In [ ]:
# get elements except the last column and last row
arr[:2, :3]

array([[1, 2, 4],
       [5, 6, 4]])

In [ ]:
arr[:, 1:]
# for all rows get elements after 1st column

array([[2, 4, 5],
       [6, 4, 4],
       [8, 6, 9],
       [5, 4, 6]])

In [ ]:
# from:upto
arr[0:2]

array([[1, 2, 4, 5],
       [5, 6, 4, 4]])

In [ ]:
arr = np.arange(0,10)
# arange(from no, to no.) gets all the numbers in between
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr = np.arange(0,10, step =4)
arr                                             

array([0, 4, 8])

In [ ]:
# assing all the values to 100
arr[1:] =100
arr

array([  0, 100, 100])

In [ ]:
arr = np.arange(0,10)
arr 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Array is refrenced type 
# hence the different versions are not attained 
# So use copy function
arr1 = arr.copy()
arr1[:4] =100

In [ ]:
print(arr1)
print(arr)

[100 100 100 100   4   5   6   7   8   9]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# Useful in EDA

val = 2 
arr<2

array([ True,  True, False, False, False, False, False, False, False,
       False])

In [ ]:
arr = arr *5

In [ ]:
arr[arr>4]
# get elements that are greater than 4

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
np.ones(5)
# float by default

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((3,4))
# matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
arr =   np.random.rand(3,3)

In [11]:
np.random.randint(0,100,  5)  

array([80, 19, 72, 23, 71])

In [13]:
np.random.random_sample(45)

array([0.56109072, 0.56361885, 0.06513318, 0.32229184, 0.8722962 ,
       0.94585322, 0.70185148, 0.88909884, 0.59887103, 0.30555157,
       0.20303723, 0.47681722, 0.54653154, 0.83791493, 0.19811992,
       0.4454553 , 0.33430985, 0.08813523, 0.5156316 , 0.24501809,
       0.59036621, 0.69536919, 0.25367035, 0.11454179, 0.35869069,
       0.9120424 , 0.3147421 , 0.68065237, 0.03903953, 0.53935003,
       0.71383912, 0.15223695, 0.22507648, 0.55245333, 0.93341295,
       0.03821996, 0.11059892, 0.78936113, 0.89051611, 0.94083114,
       0.29523093, 0.93706566, 0.92094583, 0.79359512, 0.06625592])